"Be iMproved
set nocompatible

"Have Pathogen
execute pathogen#infect()

" Turn on syntax highlighting please.
syntax on

" I like the default python settings for tabs...
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4

" But give preference to the indent plugins
filetype indent plugin on

" paste disables expandttab
"set paste

" Pathogen defaults
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Installed bundles, since we're going to ignore them
" pathogen
" syntastic
" bracketed-paste
" pandoc
" pandoc-syntax
